import {MyGoogleSpreadsheetv1} from "jdtksheetgoogle"
import {JWT} from "google-auth-library"
// Initialize auth - see https://theoephraim.github.io/node-google-spreadsheet/#/guides/authentication
const serviceAccountAuth = new JWT({
    // env var values here are copied from service account credentials generated by google
    // see "Authentication" section in docs for more info
    email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
    key: process.env.GOOGLE_PRIVATE_KEY,
    scopes: ['https://www.googleapis.com/auth/spreadsheets'],
  });
  const doc = new MyGoogleSpreadsheetv1('1VF7VElO8qSTAWaxIv5ovY8cOhSPr0oZ2O6wYIKp2QBQ', serviceAccountAuth);
  await doc.loadInfo(); // loads document properties and worksheets
  console.log(doc.title);
  