import 'dotenv/config';
import {GoogleSpreadsheet} from "jdtksheetgoogle"
import {JWT} from "google-auth-library"
// Initialize auth - see https://theoephraim.github.io/node-google-spreadsheet/#/guides/authentication
const serviceAccountAuth = new JWT({
    // env var values here are copied from service account credentials generated by google
    // see "Authentication" section in docs for more info
    email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
    key: process.env.GOOGLE_SERVICE_ACCOUNT_KEY.replace(/\\n/g, "\n"),
    scopes: ['https://www.googleapis.com/auth/spreadsheets'],
  });

  const doc = new GoogleSpreadsheet('171QJrvwwwfZ0HozPwTkF8fkz7Ufq7vgaD96uAmgTmK4', serviceAccountAuth);
  await doc.loadInfo(); // loads document properties and worksheets
  const sheet = doc.sheetsByTitle["CONFIGURACION"]; // or use `doc.sheetsById[id]` or `doc.sheetsByTitle[title]`
/*sheet.getCellsInRange("D50:D63").then(cells => {
    console.log(cells);
})*/


console.log(sheet.rowCount);
 